# 4.7_numpy_exercises.py
## Q's 1-7

#### Hackney, Chad
#### 12 Mar 19

In [4]:
# Exercises
# Create a file named 4.7_numpy_exercises.py for this exercise.

# Use the following code for the questions below:
#       a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

 #  

#### ** Setting up environment:

In [5]:
import numpy as np
import math

In [6]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
type(a)

numpy.ndarray

In [7]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

#### 1. How many negative numbers are there?

In [8]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
less_than_zero = a < 0
less_than_zero

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [9]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a[a < 0]

array([-2, -1, -6, -7])

In [10]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
less_than_zero = a < 0
less_than_zero.sum()

4

#### 2. How many positive numbers are there?

In [11]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

greater_than_zero = a > 0
greater_than_zero

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [12]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

a[a > 0]

array([ 4, 10, 12, 23,  3])

In [13]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

greater_than_zero = a > 0
greater_than_zero.sum()

5

#### 3. How many EVEN and POSITIVE numbers are there?

In [14]:
# array divisible by zero, ie "even number", AND is even number
## create a new array 'b', to preserve 'a' intact.
b = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

c = b[(b % 2) == 0]
c = c > 0
c.sum()

3

#### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [15]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

d = a + 3
d = d > 0
d.sum()

10

#### 5. If you squared each number, what would the new mean and standard deviation be?

In [16]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

e = a ** 2  # when printing out just 'e', this works so far to square each... now get the mean and std for 'e'
print(e)
print(e.mean())
print(e.std())

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516


#### 6.  A common statistical operation on a dataset is centering.  This means to adjust the data such that the center of the data is at 0.  This is done by subtracting the mean from each data point.  Center the data set.

In [17]:
# This is the 'x' or "array of values", minus the mean of those values.

f = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
g = f.mean()
h = f - g
h

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

#### 7.  Calculate the z-score for each data point. Recall that the z-score is given by: 
Z = x−μ / σ

In [18]:
# The problem above at #6 is literally the top half of this equation in #7.
# Now, simply divide #6 above, by the standard deviation of that array of data.

i = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
j = i.mean()
k = i.std()
l = (i - j) / k
l

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## Setup 1:
#### 8.  Copy the setup and exercise directions from More_Numpy_Practice  /missing weblink/   into your 4.7_numpy_exercises.py and add your solutions.
#### ** Setting up environment:

In [19]:
import numpy as np
import math

In [20]:
## Setup 1
#  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#  Use python's built in functionality/operators to determine the following:

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(a)

numpy.ndarray

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 8.1.1  Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [23]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sum_of_a = a.sum()
sum_of_a

55

#### 8.1.2. Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [24]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

min_of_a = a.min()
min_of_a

1

#### 8.1.3. Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

max_of_a = a.max()
max_of_a

10

#### 8.1.4. Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean_of_a = a.mean()
mean_of_a

5.5

#### 8.1.5. Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [27]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

product_of_a = a.prod()
product_of_a

3628800

#### 8.1.6. Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [28]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### 8.1.7. Exercise 7 - Make a variable named odds_in_a.  It should hold only the odd numbers.

In [29]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odds_in_a = a[a % 2 == 1]
odds_in_a

array([1, 3, 5, 7, 9])

#### 8.1.8. Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

## Setup 2:

#### What about life in two dimensions?  A list of lists is matrix, a table, a spreadsheet, a chessboard...
#### Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [31]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [32]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

type(b)

numpy.ndarray

In [33]:
b

array([[3, 4, 5],
       [6, 7, 8]])

#### 8.2.1. # Exercise 1 - refactor the following to use numpy.  Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [34]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

sum_of_b = b.sum()
sum_of_b

33

#### 8.2.2. Exercise 2 - refactor the following to use numpy. 

In [35]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = b.min()
min_of_b

3

#### 8.2.3. Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [36]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = b.max()
max_of_b

8

#### 8.2.4. Exercise 4 - refactor the following using numpy to find the mean of b

In [37]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# mean_of_b = (sum(b[0]) + sum(b[1])) / (len([b[0]]) + len(b[1]))

mean_of_b = b.mean()
mean_of_b

5.5

#### 8.2.5. Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [38]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

product_of_b = b.prod()
product_of_b

20160

#### 8.2.6. Exercise 6 - refactor the following to use numpy to find the list of squares

In [39]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

#### 8.2.7. Exercise 7 - refactor using numpy to determine the odds_in_b

In [40]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

#### 8.2.8. Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [41]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

#### 8.2.9. Exercise 9 - print out the shape of the array b.

In [42]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

b.shape

(2, 3)

#### 8.2.10. Exercise 10 - transpose the array b.

In [43]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

#### 8.2.11. Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [44]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

#### 8.2.12. Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [45]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
]
)

b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [46]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [47]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)
type(c)

numpy.ndarray

In [48]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 8.3.1 Exercise 1 - Find the min, max, sum, and product of c.

In [49]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

min_of_c = c.min()
print(f'min_of_c: {min_of_c}')

max_of_c = c.max()
print(f'max_of_c: {max_of_c}')

sum_of_c = c.sum()
print(f'sum_of_c: {sum_of_c}')

product_of_c = c.prod()
print(f'product_of_c: {product_of_c}')


min_of_c: 1
max_of_c: 9
sum_of_c: 45
product_of_c: 362880


#### 8.3.2. Exercise 2 - Determine the standard deviation of c.

In [50]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

standard_deviation = c.std()
print(f'standard_deviation: {standard_deviation}')

standard_deviation: 2.581988897471611


#### 8.3.3. Exercise 3 - Determine the variance of c.

In [51]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

variance = c.var()
print(f'variance: {variance}')

variance: 6.666666666666667


#### 8.3.4. Exercise 4 - Print out the shape of the array c

In [52]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

c.shape

(3, 3)

#### 8.3.5. Exercise 5 - Transpose c and print out transposed result.

In [53]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

transpose_c = c.transpose()
print(f'transpose_c:\n {transpose_c}')

transpose_c:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 8.3.6. Exercise 6 - Multiply c by the c-Transposed and print the result.

In [54]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

c_by_t_posed_c = c * transpose_c
print(f'c_by_t_posed_c:\n {c_by_t_posed_c}')

c_by_t_posed_c:
 [[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]



#### 8.3.7. Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261.

In [55]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

print(f'Sum of t_posed_c: {c_by_t_posed_c.sum()}')

Sum of t_posed_c: 261


#### 8.3.8. Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [56]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

prod_of_c = c.prod()
print(f'product of c: {prod_of_c}')

prod_of_c_t_pose = transpose_c.prod()
print(f'product of c-transposed: {prod_of_c_t_pose}')


prod_of_c_by_prod_of_c_t_pose = prod_of_c * prod_of_c_t_pose
print(f'product of c, multiplied the product of c-transposed: {prod_of_c_by_prod_of_c_t_pose}')
print('... so, transposing an array does not affect its product.')

product of c: 362880
product of c-transposed: 362880
product of c, multiplied the product of c-transposed: 131681894400
... so, transposing an array does not affect its product.


## Setup 4:

In [57]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [58]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)
type(d)

numpy.ndarray

In [59]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

#### 8.4.1. Exercise 1 - Find the sine of all the numbers in d.

In [60]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### 8.4.2. Exercise 2 - Find the cosine of all the numbers in d

In [61]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### 8.4.3. Exercise 3 - Find the tangent of all the numbers in d

In [62]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### 8.4.4. Exercise 4 - Find all the negative numbers in d

In [63]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

neg_nos_in_d = d[d < 0]
print(neg_nos_in_d)

[-90 -30 -45 -45]


#### 8.4.5. Exercise 5 - Find all the positive numbers in d

In [64]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

pos_nos_in_d = d[d > 0]
print(pos_nos_in_d)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


#### 8.4.6 Exercise 6 - Return an array of only the unique numbers in d.

In [65]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### 8.4.7. Exercise 7 - Determine how many unique numbers there are in d.

In [66]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

np.unique(d).shape[0]

11

#### 8.4.8 Exercise 8 - Print out the shape of d.

In [67]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

d.shape

(3, 6)

#### 8.4.9 Exercise 9 - Transpose and then print out the shape of d.

In [70]:
import numpy as np
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

# immediately below works, but the latter one below is prefered, like numpy shorthand
# d_t_pose = d.transpose()
# d_t_pose.shape

# preferred
np.transpose(d).shape

(6, 3)

#### 8.4.10 Exercise 10 - Reshape d into an array of 9 x 2

In [69]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

#### end of 4.7_numpy_exercises