In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
type(a)
# this creates an array by feeding it the list of [1,2,3]
# the type(a) just tells the type of this array
# the array is an .ndarray

numpy.ndarray

In [14]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# this creates a 3 x 3 matrix, or a "list of lists" or "list of arrays", to create the array below, notice the correct bracket placement

In [15]:
a
# this calls the array named 'a' from cells above

array([1, 2, 3])

In [24]:
a[1:]
# this calls the first array in the list of arrays from array named 'a' from cells above
# this grabs everything from the index of 1 to the end

a[:2]
# this grabs from the beginning up to (but not incl) 2

a[1:3]
#this extracts from 1 to 3 (not including 3)

array([2, 3])

In [17]:
m
# this calls the array named 'm' from above

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
m[0]
# this calls the first array in the list of arrays from array named 'm' above, which is the first array in 'm'

array([1, 2, 3])

In [19]:
m[1,2]
# this calls the middle array from the array named 'm', and references the last character in that array.

6

In [25]:
a.shape
# this asks numpy to describe the shape, in this case, 3 items in an array, a 1 dimensional matrix

(3,)

In [26]:
m.shape
# asks numpy to describe the shape, in this case, 3 items in 3 arrays, OR a '3 by 3 matrix'

(3, 3)

In [29]:
# ''[1, 2, 3] + 1' this generates an error

# But with numpy (see below), it works:
np.array([1, 2, 3]) + 1    

array([2, 3, 4])

In [30]:
# see above, more of the same:
m + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [31]:
# but adding one to the array 'm' is temporary and does not re-assign M to include that 1
# check by calling m again:
m

# this is called 'vectorized operations'

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# more:
m - 4

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [33]:
m * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [34]:
m / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [35]:
m ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
# look at 'a' again:
a

array([1, 2, 3])

In [40]:
# now, slice into a, to pull back various pieces by "indexing an array"
a[[True, False, True]]

array([1, 3])

In [41]:
indexes_to_keep = [True, False, True]
a[indexes_to_keep]

array([1, 3])

In [42]:
# creating the formula below (a % 2 == 1) tells it to create that condition and feed it into the array 'a' to index into it
a[(a % 2) == 1]

array([1, 3])

In [98]:
# numbers greatet than or equal to 2
indexes = a >= 2
numbers_greater_than_or_equal_to = a[indexes]
#or

a[indexes]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
a[a >= 2]
# all the values in 'a' that are greater than or equal to 2

array([2, 3])

In [45]:
a[a < 2]
# similar, it returns all the values in 'a' that are less than 2, and displays back as numpy arrays

array([1])

In [47]:
# these operations return "numpy indimensional array of booleans"
# because a was designated as an arrary, when grabbing those values in 'a', it still returns the values in an array of boolean values

In [48]:
np.random.randn(10)
# this generates ten random numbers, about half positive and half below

array([ 0.59262992,  0.25239751,  1.05551495, -0.45209336, -0.63868964,
        0.9482584 , -0.4031911 , -0.017057  , -0.75036894, -0.93473293])

In [96]:
n = 1000
np.random.randn(n)
greater_than_zero = a > 0
# for every element in a, generate an value greater than zero
# greater_than_zero ... run this to return the actual items
greater_than_zero

#greater_than_zero.sum()
#this sums the returned items, without showing them


# n_true = greater_than_zero.sum() # number of true values from the greater_than_zero array
# n_true / a.shape[0] # take the number of true values and divide by the number of elements in the array
# give the percentage of true values


# *****   GET HELP ON THIS, I DON'T UNDERSTAND THIS LAST PIECE!!!!!   *****
# specifically, the n_true and the shape thing.  Is this referring back to array 'a' ?


array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [62]:
0.9090909090909091

np.random.randn(3, 2)
# 2D array

array([[ 0.53962611,  0.16310795],
       [-0.12031235, -0.91994643],
       [ 0.5732629 , -0.03187347]])

In [63]:
np.random.randn(3, 3, 3)
# 3 D array

array([[[-0.9281473 , -0.62808056, -0.35577115],
        [ 0.45232531,  0.53844674,  0.72139131],
        [-0.66355034, -0.57675873,  1.17125957]],

       [[-0.31061919,  0.02858447,  0.94266058],
        [ 0.80690382, -1.61317113, -0.56425916],
        [ 0.2004856 , -2.4674631 ,  2.77194006]],

       [[ 0.04394599, -0.45467558, -1.7535857 ],
        [ 0.74297972,  1.02085976,  1.58883896],
        [ 0.94388456, -0.80108138, -0.69914274]]])

In [64]:
# The standard distribution has a mean of 0, and a stdev of 1
# this is where everything is relatively evenly balanced around the mean at 0, with the stdevs -1-3 on the left and 1-3 on the right
# if we want a different distribution, say skewed one way or the other:

grades = np.random.rand(20) * 10 + 1
# grades = np.random.rand(number of items wanted from the random generator) multiplied by the standard deviation,
# and then adding the mean.


In [68]:
# So now feed this numbers to calculate:

mean = 80
standard_deviation = 10
number_of_items_to_return = 20
grades = np.random.rand(number_of_items_to_return) * standard_deviation + mean
grades  # using 'grades' simply calls this function to operate and run the formula and generate the result

# I can now change the mean / stdev / number of items to return input fields to generate new info

array([81.34036203, 88.71594253, 81.17670496, 87.60085584, 84.69497869,
       88.78747621, 89.02491879, 85.64818792, 85.11281574, 87.81198978,
       80.44945086, 81.80847095, 83.52523147, 82.85362445, 85.48132056,
       80.56458273, 86.42830005, 82.4868231 , 82.6111613 , 85.39120218])

In [69]:
# or
grades.mean()

84.5757200070965

In [70]:
np.arange(4)
# this creates an array based on the inserted range of 4

array([0, 1, 2, 3])

In [77]:
np.arange(11)
# this creates an array based on the inserted range of 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
np.linspace(0, 10, 11)
# this generates an array of 10 numbers, from 1 to 10

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [75]:
np.linspace(0, 10, 15)
# this generates an array of 15 numbers, from 1 to 10

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [79]:
a = np.linspace(0, 10, 11)

In [83]:
a.min()
a.mean()
a.max()

10.0

In [84]:
a.std()

3.1622776601683795

In [99]:
# in sql:
x = 3
x > 2 and x <6

# in python, this is acceptable:
2 < x <6

True

In [102]:
# ending lines of python code with a comma, makes python think you're creating a tuple:
x = 1, # <-- note comma here

type(x)

tuple

In [103]:
x = 1 # <-- note NO comma here

type(x)
# removing the comma makes it an int

int

In [104]:
%timeit np.random.rand(100_000) + 1#test how long it takes to add 1 to 100,000 numbers

1.2 ms ± 32.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# similarly, using a double %%timeit runs everything in the cell in jupyter, so if you have multiple
# equations or pieces of code running, it runs them all and test the time to do so.